name: time2mix
description: Application that leverages Google Gemini for discovering and matching cocktail recipes. Users can search for recipes or input available ingredients to find suitable cocktail options.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  envied: ^0.5.3
  equatable: ^2.0.5
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.1
  google_generative_ai: ^0.2.2
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  generate: true
